/*1*/
SELECT EMPRESA, POBLACION FROM CLIENTES;

/*2*/
SELECT  NOMBREARTICULO, SECCION FROM PRODUCTOS WHERE SECCION = 'CERAMICA';

/*3*/
SELECT NOMBREARTICULO,PRECIO FROM PRODUCTOS
WHERE PRECIO BETWEEN 100 AND 200;

/*4*/
SELECT  NOMBREARTICULO, PAISDEORIGEN FROM PRODUCTOS
WHERE PAISDEORIGEN NOT IN ('ESPAÑA');

/*5*/
SELECT NOMBREARTICULO, SECCION, PRECIO, PAISDEORIGEN FROM PRODUCTOS
WHERE PAISDEORIGEN = 'ESPAÑA' AND SECCION = 'DEPORTES' OR PRECIO > 350;

/*6*/
SELECT NOMBREARTICULO, PAISDEORIGEN, FECHA FROM PRODUCTOS
WHERE  PAISDEORIGEN ='ESPAÑA' AND FECHA BETWEEN  '02-01-2002' AND '03-01-2002'
ORDER BY NOMBREARTICULO DESC;

/*7*/
SELECT EMPRESA, DIRECCION, POBLACION FROM CLIENTES
ORDER BY CLIENTES.POBLACION ASC, CLIENTES.DIRECCION DESC;

/*8*/
SELECT * FROM CLIENTES
ORDER BY POBLACION ASC;

/*9*/
SELECT DIRECCION, TELEFONO, POBLACION AS RESIDENCIA FROM CLIENTES
ORDER BY POBLACION DESC;

/*10*/
SELECT POBLACION FROM CLIENTES;

/*11*/
SELECT SECCION, AVG(PRECIO) AS "SUMA POR SECCION" FROM PRODUCTOS
GROUP BY SECCION;

/*12*/
SELECT SECCION, AVG(PRECIO) AS "MEDIA POR SECCION" FROM PRODUCTOS
WHERE SECCION NOT IN ('JUGUETERIA')
GROUP BY SECCION;

/*13*/
SELECT COUNT(SECCION) FROM PRODUCTOS
WHERE SECCION = 'DEPORTES';

/*14*/
SELECT NOMBREARTICULO, SECCION, PRECIO, round(PRECIO * 0.7,2) AS DESCUENTO_7 FROM PRODUCTOS;

/*15*/
SELECT FECHA, SECCION, NOMBREARTICULO, PRECIO, ROUND(PRECIO - 2,2)
AS "“DTO2 €_EN_CERÁMICA" FROM PRODUCTOS
WHERE SECCION = 'CERÁMICA' ORDER BY FECHA DESC;

/*16*/
SELECT NOMBREARTICULO, SECCION, PRECIO FROM PRODUCTOS ;
